
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Community from './models/Community.js';
import User from './models/User.js';

dotenv.config();

const debugCommunity = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log("Connected to DB");

        const hasCommunityId = '6979adbd1473c3988c29902d'; // from user logs (though look suspiciously like custom text, assuming it is valid ObjectId if 24 hex chars)
        // Wait, '6979adbd1473c3988c29902d' is 24 chars? 
        // 6979adbd1473c3988c29902d -> 6+18 = 24. It looks valid hex. (Actually likely generated by some tool or random, but valid format)

        // Actually the logs showed: community Id:  6979adbd1473c3988c29902d
        // And previous logs: 696dfa2ef719afa4b326eb94

        // Let's check both or list all.
        const communities = await Community.find({});
        console.log(`Found ${communities.length} communities.`);

        for (const comm of communities) {
            console.log(`\nCommunity: ${comm.name} (ID: ${comm._id})`);
            console.log(`Creator: ${comm.creator}`);
            console.log(`Authorized Persons: ${comm.authorizedPersons}`);

            // Find creator details
            const creator = await User.findById(comm.creator);
            console.log(`Creator Details: ${creator ? creator.email + ' (' + creator.fullName + ')' : 'NOT FOUND'}`);
        }

    } catch (error) {
        console.error("Error:", error);
    } finally {
        await mongoose.connection.close();
    }
};

debugCommunity();
